-- MySQL Script generated by MySQL Workbench
-- Wed Aug 31 16:00:32 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mybus
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mybus` ;

-- -----------------------------------------------------
-- Schema mybus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mybus` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `mybus` ;

-- -----------------------------------------------------
-- Table `mybus`.`vehicle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mybus`.`vehicle` ;

CREATE TABLE IF NOT EXISTS `mybus`.`vehicle` (
  `vId` INT(11) NOT NULL AUTO_INCREMENT,
  `vTitle` VARCHAR(255) NOT NULL,
  `vDescription` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`vId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mybus`.`ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mybus`.`ticket` ;

CREATE TABLE IF NOT EXISTS `mybus`.`ticket` (
  `tId` INT(11) NOT NULL AUTO_INCREMENT,
  `tTitle` VARCHAR(255) NOT NULL,
  `tDesc` VARCHAR(255) NOT NULL,
  `tPhoto` VARCHAR(255) NOT NULL,
  `tPrice` DOUBLE NOT NULL,
  `tDiscount` DOUBLE NOT NULL,
  `tQuantity` INT(11) NOT NULL,
  `vId` INT(11) NOT NULL,
  PRIMARY KEY (`tId`),
  INDEX `ticket_vId_idx` (`vId` ASC) ,
  CONSTRAINT `ticket_vId`
    FOREIGN KEY (`vId`)
    REFERENCES `mybus`.`vehicle` (`vId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mybus`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mybus`.`user` ;

CREATE TABLE IF NOT EXISTS `mybus`.`user` (
  `userId` INT(11) NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(255) NOT NULL,
  `userEmail` VARCHAR(255) NOT NULL,
  `userPassword` VARCHAR(255) NOT NULL,
  `userPhone` INT(11) NOT NULL,
  `userPic` VARCHAR(255) NOT NULL,
  `userAddress` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
